# Generated by Django 3.2.18 on 2023-10-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item_item_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
    ]
