# Generated by Django 3.2.18 on 2023-10-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_remove_item_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quality',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used')], default='new', max_length=10),
        ),
    ]
