# Generated by Django 3.2.18 on 2023-09-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='has_unread_messages',
            field=models.BooleanField(default=False),
        ),
    ]
