# Generated by Django 3.2.18 on 2023-09-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_conversation_has_unread_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='has_unread_messages',
            field=models.BooleanField(default=False),
        ),
    ]
